tasks:
  # KUBE_CONFIG is kubernetes auth info. https://www.linode.com/docs/guides/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/
  # to update KUBE_CONFIG: `gp env KUBE_CONFIG=$(base64 -w 0 new-config-file.yaml)`
  # https://gitpod.io/variables
  # https://github.com/erosson/multiplayer/settings/secrets/actions
  - before: |
      ./vendor/config_kube.sh || true
      source ./vendor/bashrc
      echo "source $PWD/vendor/bashrc" >> ~/.bashrc
    command: yarn start

vscode:
  extensions:
    - arcanis.vscode-zipfs
    - esbenp.prettier-vscode
    - zxh404.vscode-proto3
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-azuretools.vscode-docker
