tasks:
  # KUBE_CONFIG is kubernetes auth info. https://www.linode.com/docs/guides/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/
  # to update KUBE_CONFIG: `gp env KUBE_CONFIG=$(base64 -w 0 new-config-file.yaml)`
  # https://gitpod.io/variables
  # https://github.com/erosson/multiplayer/settings/secrets/actions
  - before: |
      mkdir -p $HOME/.kube && echo $KUBE_CONFIG | base64 -di > $HOME/.kube/config || true
      echo "source $PWD/vendor/path.sh" >> ~/.bashrc
    command: yarn start

vscode:
  extensions:
    - arcanis.vscode-zipfs
    - esbenp.prettier-vscode
    - zxh404.vscode-proto3
    - ms-kubernetes-tools.vscode-kubernetes-tools
