# https://www.linode.com/docs/guides/how-to-deploy-a-static-site-on-linode-kubernetes-engine/#next-steps
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
  # namespace: hugo-site
spec:
  # need 3 pods for reliability, but I'm still learning, and also a cheapass
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: ghcr.io/erosson/multiplayer/www:main
        imagePullPolicy: Always
        ports:
        - containerPort: 80
