apiVersion: v1
kind: Service
metadata:
  name: server-service-lb
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
    # https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
    external-dns.alpha.kubernetes.io/hostname: multiplayer-test.erosson.org
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: server
  sessionAffinity: None
